sudo: false
language: python

cache: pip

python:
  - "3.5"
  - "3.4"
  - "3.3"
  - "2.7"

env:
  - DJANGO="Django>=1.10,<1.11"
  - DJANGO="Django>=1.9,<1.10"
  - DJANGO="Django>=1.8,<1.9"
  - DJANGO="https://github.com/django/django/archive/master.tar.gz"

matrix:
  exclude:
    - python: "3.3"
      env: DJANGO="Django>=1.10,<1.11"
    - python: "3.3"
      env: DJANGO="Django>=1.9,<1.10"
    - python: "3.3"
      env: DJANGO="https://github.com/django/django/archive/master.tar.gz"
  allow_failures:
    - env: DJANGO="https://github.com/django/django/archive/master.tar.gz"

install:
  - travis_retry pip install $DJANGO
  - travis_retry pip install psycopg2==2.6.1
  - travis_retry pip install celery==4.0.0
  - travis_retry pip install futures     # For python 2.7
  - travis_retry pip install sorl-thumbnail>=12.3  
  - travis_retry pip install mock 
  - travis_retry pip install python-magic>=0.4.12 # For python 2.7

services:
  - postgresql

script:
- python -Wall runtests.py

deploy:
  provider: pypi
  user: "vk-sharma"
  password:
    secure: !!python/unicode 'UA1lElW0Y1BbDv0mf2jAsvnFCGpSNnhm+0bB8uOdtVGE51q78UKLV/LbSFbOflaM1iOhmNHAfZs2KTcrPPdQgqthY5MQA9YhnSq9nsr9PTwEUyiQPtorh3jpjfj5UYKz7Cjf+KQNrdhRMHSI62D4xL8rL9ZLvFKsApy/z6/o/Pls4E5ZAbmsfNHHSVvVKTDlkC8bzJEmWN+QaJhcPATAUXR2ESuQcRJFemnBY+86+kf5qfoVSt9MxWeUn0NVu1WDkN1HaxDobqP0y3Bwlf57t37EVfPXkoGSZrPY19sZ7AOVzIkdIkhyKyXwdZXLyhj1BPi8BFLTKiSomFq8k1abivHGVojRwRCAEzA4T1BWR08rlmaNwGTPp7M7NXfOqaFaYcTUKaGnyTAe7gI8/bRcyx+xIzbgaTprEIlOpkPGT+LeUmISHII0HHRFruaNS8K81+1vOCDl/Mrhp/U747uQQHKqVkWIEp97iO0OAd+uMJwZFepPqGFDIdJexSIvCOdqfK+7Xt/qOqtxgKwN1fGim1lp9ZMhcSwhFX2PvRpgnQWf20cIUaIleEP0K0cLLRSwOT81Vmkp2jKN8C/OWyYwbON6uamV92k7DPD/ZpOMcY8XUB/OZoKax6H0wzv2NxAQCGzjmltGvy2R+ZfTn1jHHhhxUcZ6W/8HGvFtU/3cgnc='
  on:
    tags: true
